"""Added columns

Revision ID: 623ddd5a7e4c
Revises: 
Create Date: 2024-06-03 11:23:53.348939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '623ddd5a7e4c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trailer_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('release_year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('duration', sa.Interval(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_column('duration')
        batch_op.drop_column('release_year')
        batch_op.drop_column('trailer_url')

    # ### end Alembic commands ###
