"""Updating duration column

Revision ID: cedb4782f676
Revises: 623ddd5a7e4c
Create Date: 2024-06-03 16:04:10.514834

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cedb4782f676'
down_revision = '623ddd5a7e4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.alter_column('duration',
               existing_type=postgresql.INTERVAL(),
               type_=sa.String(length=30),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.alter_column('duration',
               existing_type=sa.String(length=30),
               type_=postgresql.INTERVAL(),
               existing_nullable=True)

    # ### end Alembic commands ###
